version: "2"
services:
  peephole:
    image: peephole
    build: .
    volumes:
      - ./build/peephole:/usr/bin/peephole:ro
      - ./config.json:/etc/peephole/config.json:ro
    command: >-
      /usr/bin/peephole
      --config /etc/peephole/config.json
      --debug
    ports: []
    links: []
