version: "2"
services:
  peephole:
    image: peephole
    build: .
    volumes:
      - ./build/peephole:/usr/bin/peephole:ro
      - ./config.yaml:/etc/peephole/config.yaml:ro
    command: >-
      /usr/bin/peephole
      --config /etc/peephole/config.yaml
    ports: []
    links: []
